runtime: python310  # Use python39 or python38 if needed

entrypoint: gunicorn -b :$PORT app:server

instance_class: F1  # Optional: defines the compute class (F1 = free tier eligible)

env_variables:
  FLASK_ENV: production

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2

handlers:
- url: /.*
  script: auto
